// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourCarBud.WebApi.Modules.DbContextModule;

namespace YourCarBud.WebApi.Migrations
{
    [DbContext(typeof(YourCarBudDbContext))]
    partial class YourCarBudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderModule.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ContactDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeliveryAppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderModule.Entities.OrderStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStep");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderStepModule.Entities.ContactDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ContactDetail");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderStepModule.Entities.DeliveryAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppointmentDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("DeliveryAppointment");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderStepModule.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderModule.Entities.OrderStep", b =>
                {
                    b.HasOne("YourCarBud.WebApi.Modules.OrderModule.Entities.Order", "Order")
                        .WithMany("OrderSteps")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderStepModule.Entities.ContactDetail", b =>
                {
                    b.HasOne("YourCarBud.WebApi.Modules.OrderModule.Entities.Order", "Order")
                        .WithOne("ContactDetail")
                        .HasForeignKey("YourCarBud.WebApi.Modules.OrderStepModule.Entities.ContactDetail", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderStepModule.Entities.DeliveryAppointment", b =>
                {
                    b.HasOne("YourCarBud.WebApi.Modules.OrderModule.Entities.Order", "Order")
                        .WithOne("DeliveryAppointment")
                        .HasForeignKey("YourCarBud.WebApi.Modules.OrderStepModule.Entities.DeliveryAppointment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderStepModule.Entities.Payment", b =>
                {
                    b.HasOne("YourCarBud.WebApi.Modules.OrderModule.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("YourCarBud.WebApi.Modules.OrderStepModule.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YourCarBud.WebApi.Modules.OrderModule.Entities.Order", b =>
                {
                    b.Navigation("ContactDetail");

                    b.Navigation("DeliveryAppointment");

                    b.Navigation("OrderSteps");

                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
